spring:
  application:
    name: zuk-api

  datasource:
    url: jdbc:postgresql://localhost/zuk-api-db
    username: postgres_1
    password: postgresQL

    hikari:
      auto-commit: false

  jpa:
    show-sql: false
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: update

# JWT
zuk:
    jwtSecret: zukSecretKey
    jwtExpirationMs: 86400000

fileStorage:
     url: http://85.214.194.89:8766/dropbox/